######################################################################
# Automatically generated by qmake (2.01a) Wed Aug 15 11:28:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .


DEFINES += OPENCV_ENABLED
LIBS += -L/usr/local/lib -lcv -lcxcore -L/opt/OpenCV-2.1.0/lib
INCLUDEPATH += /opt/OpenCV-2.1.0/include

# Input
HEADERS += WarpWindow.h
SOURCES += WarpWindow.cpp WarpTest.cpp
